<AiFace>
    BoxLayout:
        size: root.size
        orientation: "vertical"
        size_hint: 1, 0.1
        TextInput:
            id: text_input_1
            text: "Your message here"
            on_focus:
                self.text = ""
        Button:
            id: button1
            text: "Send\nNudes"
            on_press:
                root.send_answer()
        Label:
            id: label1
            text: root.label_text